name = "requesttoqueue"
main = "src/worker.ts"
compatibility_date = "2023-07-17"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/queues/get-started
[[queues.producers]]
binding = "MY_QUEUE"
queue = "my-queue"


 [[r2_buckets]]
binding = 'queue-push-worker-BUCKET' # <~ valid JavaScript variable name
bucket_name = "queue-push-worker"